# -*- coding: utf-8 -*-
"""intraday_crypto_game_theory.py (copy).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHw9JqVK4X2CWfN-nmCjPL9wOSZ1QcG7
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta, timezone
from streamlit_autorefresh import st_autorefresh

# 1. Налаштування сторінки
st.set_page_config(page_title="Game Theory Trader", layout="wide")

# --- БЛОК ТАЙМЕРА (UTC+2) ---
kyiv_tz = timezone(timedelta(hours=2))

def get_now():
    return datetime.now(kyiv_tz)

refresh_minutes = 5
st_autorefresh(interval=1000, key="timer_refresh")

if 'next_update' not in st.session_state:
    st.session_state.next_update = get_now() + timedelta(minutes=refresh_minutes)

remaining = (st.session_state.next_update - get_now()).total_seconds()

if remaining <= 0:
    st.cache_data.clear()
    st.session_state.next_update = get_now() + timedelta(minutes=refresh_minutes)
    st.rerun()

st.sidebar.markdown(f"🕒 Поточний час (UTC+2): **{get_now().strftime('%H:%M:%S')}**")
st.sidebar.markdown(f"### ⏳ Оновлення через: `{int(max(0, remaining))//60:02d}:{int(max(0, remaining))%60:02d}`")

if st.sidebar.button("🔄 Оновити зараз"):
    st.cache_data.clear()
    st.session_state.next_update = get_now() + timedelta(minutes=refresh_minutes)
    st.rerun()

st.title("📊 Інтрадей Термінал: Теорія Ігор")
st.sidebar.header("Налаштування стратегії")

symbol = st.sidebar.selectbox("Оберіть актив", ["BTC-USD", "ETH-USD", "SOL-USD", "AAPL", "NVDA"])
period = st.sidebar.slider("Період аналізу (дні)", 1, 7, 5)
window = st.sidebar.number_input("Вікно Z-Score (свічки)", value=200)
whale_sens = st.sidebar.slider("Чутливість до китів", 1.5, 4.0, 2.5)

@st.cache_data(ttl=300)
def get_data(symbol, period):
    try:
        df = yf.download(symbol, period=f"{period}d", interval='5m', progress=False, auto_adjust=True)
        if df.empty: return pd.DataFrame()
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        df = df.loc[:, ~df.columns.duplicated()]
        df = df.dropna(subset=['Close'])
        return df
    except Exception as e:
        st.error(f"Помилка завантаження: {e}")
        return pd.DataFrame()

data = get_data(symbol, period)

if not data.empty and len(data) > window:
    df_calc = data.copy()
    df_calc.index = pd.to_datetime(df_calc.index)
    df_calc['Date_Only'] = df_calc.index.date  # Додано назад!

    # Z-Score
    df_calc['Mean'] = df_calc['Close'].rolling(window=int(window)).mean()
    df_calc['Std'] = df_calc['Close'].rolling(window=int(window)).std()
    df_calc['Z_Score'] = (df_calc['Close'] - df_calc['Mean']) / df_calc['Std']

    # Надійний VWAP (тепер з правильними відступами)
    df_calc['Price_Vol'] = df_calc['Close'] * df_calc['Volume']
    df_calc['VWAP'] = df_calc.groupby('Date_Only')['Price_Vol'].cumsum() / df_calc.groupby('Date_Only')['Volume'].cumsum()

    # Кити та Айсберги
    vol_mean = df_calc['Volume'].rolling(20).mean()
    df_calc['Whale'] = df_calc['Volume'] > (vol_mean * whale_sens)
    price_pct = df_calc['Close'].pct_change().abs()
    df_calc['Iceberg'] = (price_pct < 0.0005) & (df_calc['Volume'] > vol_mean * 1.8)

    final_df = df_calc.dropna(subset=['Z_Score', 'VWAP']).copy()

    if not final_df.empty:
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 12), sharex=True)
        plt.subplots_adjust(hspace=0.1)

        ax1.plot(final_df.index, final_df['Close'], label='Price (5m)', color='black', alpha=0.6)
        ax1.plot(final_df.index, final_df['VWAP'], label='Intraday VWAP', color='orange', lw=2)

        whales = final_df[final_df['Whale']]
        icebergs = final_df[final_df['Iceberg']]
        ax1.scatter(whales.index, whales['Close'], color='red', label='Whale', s=60, marker='^', zorder=5)
        ax1.scatter(icebergs.index, icebergs['Close'], color='blue', label='Iceberg', s=60, marker='s', zorder=5)
        ax1.legend(loc='upper left')
        ax1.grid(True, alpha=0.2)

        ax2.plot(final_df.index, final_df['Z_Score'], color='purple', label='Z-Score', lw=1.5)
        ax2.axhline(2.5, color='red', ls='--', alpha=0.5)
        ax2.axhline(-2.5, color='green', ls='--', alpha=0.5)
        ax2.fill_between(final_df.index, 2.5, final_df['Z_Score'], where=(final_df['Z_Score'] > 2.5), color='red', alpha=0.2)
        ax2.fill_between(final_df.index, -2.5, final_df['Z_Score'], where=(final_df['Z_Score'] < -2.5), color='green', alpha=0.2)

        ax2.xaxis.set_major_locator(mdates.HourLocator(interval=2))
        ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M\n%d.%m'))
        ax2.grid(visible=True, which='major', color='gray', alpha=0.3)

        st.pyplot(fig)

        col1, col2, col3 = st.columns(3)
        last_row = final_df.iloc[-1]
        with col1: st.metric("Ціна", f"${last_row['Close']:.2f}")
        with col2: st.metric("Z-Score", f"{last_row['Z_Score']:.2f}")
        with col3:
            if last_row['Z_Score'] > 2.5: st.error("🔔 ПРОДАЖ")
            elif last_row['Z_Score'] < -2.5: st.success("🔔 КУПІВЛЯ")
            else: st.info("⚖️ Рівновага")
    else:
        st.warning("Недостатньо обчислених даних.")
else:
    st.error("Дані не завантажились або їх замало.")
